package edu.gorb.musicstudio.model.dao;

import edu.gorb.musicstudio.exception.DaoException;

import java.util.List;
import java.util.Optional;

/**
 * Dao interface with base methods
 *
 * @param <T> entity type
 */
public interface BaseDao<T> {
    /**
     * Selects all entities
     *
     * @return list of found entities or empty list.
     * @throws DaoException is thrown when error while query execution occurs
     */
    List<T> findAll() throws DaoException;

    /**
     * Finds entity by id
     *
     * @param id entity id
     * @return returns optional with entity or empty optional
     * @throws DaoException is thrown when error while query execution occurs
     */
    Optional<T> findEntityById(long id) throws DaoException;

    /**
     * Inserts new entity
     *
     * @param t entity
     * @return generated by DBMS entity id or -1 if entity has no autogenerated id
     * @throws DaoException is thrown when error while query execution occurs
     */
    long insert(T t) throws DaoException;

    /**
     * Updates entity
     *
     * @param t entity
     * @throws DaoException is thrown when error while query execution occurs
     */
    void update(T t) throws DaoException;
}
