-- MySQL Script generated by MySQL Workbench
-- Sun Aug 15 14:30:34 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE =
        'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema music_studio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema music_studio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `music_studio` DEFAULT CHARACTER SET utf8;
USE `music_studio`;

-- -----------------------------------------------------
-- Table `music_studio`.`user_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `music_studio`.`user_roles`
(
    `id_user_role` INT                                  NOT NULL,
    `user_role`    ENUM ('ADMIN', 'TEACHER', 'STUDENT') NOT NULL,
    PRIMARY KEY (`id_user_role`)
)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `music_studio`.`user_statuses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `music_studio`.`user_statuses`
(
    `id_user_status` INT                                                                                       NOT NULL,
    `user_status`    ENUM ('ACTIVE', 'INACTIVE', 'ON_LEAVE', 'EMAIL_NOT_CONFIRMED', 'WAITING_FOR_APPROVEMENT') NOT NULL,
    PRIMARY KEY (`id_user_status`)
)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `music_studio`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `music_studio`.`users`
(
    `id_user`        INT          NOT NULL AUTO_INCREMENT,
    `login`          VARCHAR(20)  NOT NULL,
    `password_hash`  VARCHAR(256) NOT NULL,
    `name`           VARCHAR(20)  NOT NULL,
    `surname`        VARCHAR(20)  NOT NULL,
    `patronymic`     VARCHAR(20)  NOT NULL,
    `email`          VARCHAR(60)  NOT NULL,
    `id_user_status` INT          NOT NULL,
    `id_user_role`   INT          NOT NULL,
    PRIMARY KEY (`id_user`),
    UNIQUE INDEX `users_login_uindex` (`login` ASC) VISIBLE,
    UNIQUE INDEX `users_email_uindex` (`email` ASC) VISIBLE,
    INDEX `fk_users_user_statuses1_idx` (`id_user_status` ASC) VISIBLE,
    INDEX `fk_users_user_roles1_idx` (`id_user_role` ASC) VISIBLE,
    CONSTRAINT `fk_users_user_roles1`
        FOREIGN KEY (`id_user_role`)
            REFERENCES `music_studio`.`user_roles` (`id_user_role`),
    CONSTRAINT `fk_users_user_statuses1`
        FOREIGN KEY (`id_user_status`)
            REFERENCES `music_studio`.`user_statuses` (`id_user_status`)
)
    ENGINE = InnoDB
    AUTO_INCREMENT = 38
    DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `music_studio`.`courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `music_studio`.`courses`
(
    `id_course`      INT           NOT NULL AUTO_INCREMENT,
    `name`           VARCHAR(45)   NOT NULL,
    `description`    TEXT          NOT NULL,
    `picture_path`   VARCHAR(45)   NOT NULL,
    `price_per_hour` DECIMAL(6, 2) NOT NULL,
    `is_active`      TINYINT       NOT NULL,
    PRIMARY KEY (`id_course`)
)
    ENGINE = InnoDB
    AUTO_INCREMENT = 9
    DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `music_studio`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `music_studio`.`comments`
(
    `id_comment` INT      NOT NULL AUTO_INCREMENT,
    `id_student` INT      NOT NULL,
    `content`    TEXT     NULL DEFAULT NULL,
    `date_time`  DATETIME NOT NULL,
    `id_course`  INT      NOT NULL,
    `is_active`  TINYINT  NOT NULL,
    PRIMARY KEY (`id_comment`),
    INDEX `fk_comments_user1_idx` (`id_student` ASC) VISIBLE,
    INDEX `id_course` (`id_course` ASC) VISIBLE,
    CONSTRAINT `fk_comments_user1`
        FOREIGN KEY (`id_student`)
            REFERENCES `music_studio`.`users` (`id_user`),
    CONSTRAINT `id_course`
        FOREIGN KEY (`id_course`)
            REFERENCES `music_studio`.`courses` (`id_course`)
)
    ENGINE = InnoDB
    AUTO_INCREMENT = 10
    DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `music_studio`.`lesson_statuses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `music_studio`.`lesson_statuses`
(
    `id_lesson_status` INT                          NOT NULL,
    `status`           ENUM ('NORMAL', 'CANCELLED') NOT NULL,
    PRIMARY KEY (`id_lesson_status`)
)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `music_studio`.`subscriptions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `music_studio`.`subscriptions`
(
    `id_subscription` INT                                                                NOT NULL AUTO_INCREMENT,
    `id_student`      INT                                                                NOT NULL,
    `id_course`       INT                                                                NOT NULL,
    `date_start`      DATE                                                               NOT NULL,
    `date_end`        DATE                                                               NOT NULL,
    `lesson_amount`   INT                                                                NOT NULL,
    `status`          ENUM ('APPROVED', 'ACTIVATED', 'CANCELLED', 'WAITING_FOR_APPROVE') NOT NULL,
    PRIMARY KEY (`id_subscription`),
    INDEX `fk_subscriptions_user1_idx` (`id_student` ASC) VISIBLE,
    INDEX `fk_subscriptions_courses1_idx` (`id_course` ASC) VISIBLE,
    CONSTRAINT `fk_subscriptions_courses1`
        FOREIGN KEY (`id_course`)
            REFERENCES `music_studio`.`courses` (`id_course`),
    CONSTRAINT `fk_subscriptions_user1`
        FOREIGN KEY (`id_student`)
            REFERENCES `music_studio`.`users` (`id_user`)
)
    ENGINE = InnoDB
    AUTO_INCREMENT = 15
    DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `music_studio`.`lesson_schedules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `music_studio`.`lesson_schedules`
(
    `id_schedule`      INT      NOT NULL AUTO_INCREMENT,
    `id_student`       INT      NOT NULL,
    `id_teacher`       INT      NOT NULL,
    `id_course`        INT      NOT NULL,
    `date_time`        DATETIME NOT NULL,
    `duration`         TIME     NOT NULL,
    `id_lesson_status` INT      NOT NULL,
    `id_subscription`  INT      NULL DEFAULT NULL,
    PRIMARY KEY (`id_schedule`),
    INDEX `fk_schedule_users1_idx` (`id_student` ASC) VISIBLE,
    INDEX `fk_schedule_users2_idx` (`id_teacher` ASC) VISIBLE,
    INDEX `fk_schedule_courses1_idx` (`id_course` ASC) VISIBLE,
    INDEX `fk_lesson_schedules_lesson_statuses1_idx` (`id_lesson_status` ASC) VISIBLE,
    INDEX `lesson_schedules_subscriptions_id_subscription_fk` (`id_subscription` ASC) VISIBLE,
    CONSTRAINT `fk_lesson_schedules_lesson_statuses1`
        FOREIGN KEY (`id_lesson_status`)
            REFERENCES `music_studio`.`lesson_statuses` (`id_lesson_status`),
    CONSTRAINT `fk_schedule_courses1`
        FOREIGN KEY (`id_course`)
            REFERENCES `music_studio`.`courses` (`id_course`),
    CONSTRAINT `fk_schedule_users1`
        FOREIGN KEY (`id_student`)
            REFERENCES `music_studio`.`users` (`id_user`),
    CONSTRAINT `fk_schedule_users2`
        FOREIGN KEY (`id_teacher`)
            REFERENCES `music_studio`.`users` (`id_user`),
    CONSTRAINT `lesson_schedules_subscriptions_id_subscription_fk`
        FOREIGN KEY (`id_subscription`)
            REFERENCES `music_studio`.`subscriptions` (`id_subscription`)
)
    ENGINE = InnoDB
    AUTO_INCREMENT = 41
    DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `music_studio`.`teacher_descriptions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `music_studio`.`teacher_descriptions`
(
    `id_teacher`       INT         NOT NULL,
    `self_description` TEXT        NOT NULL,
    `experience`       INT         NOT NULL,
    `picture_path`     VARCHAR(45) NOT NULL,
    PRIMARY KEY (`id_teacher`),
    CONSTRAINT `fk_table1_users1`
        FOREIGN KEY (`id_teacher`)
            REFERENCES `music_studio`.`users` (`id_user`)
)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `music_studio`.`teacher_descriptions_has_courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `music_studio`.`teacher_descriptions_has_courses`
(
    `id_teacher` INT NOT NULL,
    `id_course`  INT NOT NULL,
    PRIMARY KEY (`id_teacher`, `id_course`),
    INDEX `fk_teacher_descriptions_has_courses_courses1_idx` (`id_course` ASC) VISIBLE,
    INDEX `fk_teacher_descriptions_has_courses_teacher_descriptions1_idx` (`id_teacher` ASC) VISIBLE,
    CONSTRAINT `fk_teacher_descriptions_has_courses_courses1`
        FOREIGN KEY (`id_course`)
            REFERENCES `music_studio`.`courses` (`id_course`),
    CONSTRAINT `fk_teacher_descriptions_has_courses_teacher_descriptions1`
        FOREIGN KEY (`id_teacher`)
            REFERENCES `music_studio`.`teacher_descriptions` (`id_teacher`)
)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `music_studio`.`teacher_schedules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `music_studio`.`teacher_schedules`
(
    `id_teacher`     INT  NOT NULL,
    `day_of_week`    INT  NOT NULL,
    `interval_start` TIME NOT NULL,
    `interval_end`   TIME NOT NULL,
    INDEX `id_teacher` (`id_teacher` ASC) VISIBLE,
    CONSTRAINT `id_teacher`
        FOREIGN KEY (`id_teacher`)
            REFERENCES `music_studio`.`users` (`id_user`)
)
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `music_studio`.`user_tokens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `music_studio`.`user_tokens`
(
    `id_token`  INT          NOT NULL AUTO_INCREMENT,
    `id_user`   INT          NOT NULL,
    `token`     VARCHAR(256) NOT NULL,
    `timestamp` DATETIME     NULL DEFAULT NULL,
    PRIMARY KEY (`id_token`),
    UNIQUE INDEX `user_tokens_id_token_uindex` (`id_token` ASC) VISIBLE,
    INDEX `id_user` (`id_user` ASC) VISIBLE,
    CONSTRAINT `id_user`
        FOREIGN KEY (`id_user`)
            REFERENCES `music_studio`.`users` (`id_user`)
)
    ENGINE = InnoDB
    AUTO_INCREMENT = 35
    DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
